### PR TITLE
recipe gui: fix caption generation for recipes

### PR DESCRIPTION
**Pull request by maniak1349**
- Fix caption generation for recipes which have probability and amount at the same time.
- Change format of probability captions slightly to make them easier to read.

### CODE REVIEW

**Comment by npo6ka** [comment]
Thank you for your help in developing the mod. I implemented this a little differently. (068cf44abd628f5c6d41624caa0442834689c470)

**Comment by maniak1349** [comment]
I still think that for probability+amount recipes "Amount x Chance Item" is a little mislead wording. It makes one think that for each recipe iteration game will roll Amount times for a single item/liquid unit with certain Chance while in reality game rolls once with Chance to get a full set of items or none at all.

**Comment by npo6ka** [comment]
How else to show it?

**Comment by maniak1349** [comment]
"Chance x Amount x Item" or "Chance  Amount x Item". It will be both more in line with basic "Amount x Item" caption and will form much more streamlined sentence when you read it:

With a chance [X%] you will get [Y] units of [ItemName].

**Pull request closed without merging**
